### ISSUE TITLE
Does not build in Xcode 6.2: variable "text" is not found as member of UILabel

### ISSUE THREAD

**Issue by Charlweed** [tejas123/XML-Parsing-using-NSXMLParse-in-Swift#1]
This does not look like a bug in your code, more a bug in Xcode. But in Xcode 6.2 (6C131e), this demo does not compile because of this line in ViewController.swift:

cell.textLabel.text = posts.objectAtIndex(indexPath.row).valueForKey("title") as NSString

 The error is:

/Volumes/projects/hymerfania/chainlinks/XML-Parsing-using-NSXMLParse-in-Swift-master/XMLParsingDemo/ViewController.swift:98:14: 'UILabel?' does not have a member named 'text'

I commented out the line to run the demo.

**Comment by Charlweed** [comment]
Did you leave out the "**?**" character? Did you intend to code "**cell.textLabel?.text**" instead of "**cell.textLabel.text**"

**Comment by tejas123** [comment]
Thanks Charlweed we fix that issue.
